apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: kiddodragon/auth
          env:
            - name: MONGO_URI
            # auth-mongo-srv comes from auth-mongo-depl.yaml file
            # auth is the name of database that we try to create
              value: 'mongodb://auth-mongo-srv:27017/auth'
            # name of Env Variable, for this auth container
            - name: JWT_KEY
              # tell Kubernetes that we want the value secret that we just create with imperative command
              valueFrom:
                # secret key reference
                secretKeyRef:
                  # name of the secret
                  name: jtw-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    # find all the pods with the label app: auth, from above from labels
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
